[{'id': 476957520,
'node_id': 'R_kgDOHG3LUA',
'name': 'WTF-Solidity',
'full_name': 'AmazingAng/WTF-Solidity',
'private': False,
'owner': {'login': 'AmazingAng', 'id': 14728591, 'node_id': 'MDQ6VXNlcjE0NzI4NTkx', 'avatar_url': 'https://avatars.githubusercontent.com/u/14728591?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/AmazingAng', 'html_url': 'https://github.com/AmazingAng', 'followers_url': 'https://api.github.com/users/AmazingAng/followers', 'following_url': 'https://api.github.com/users/AmazingAng/following{/other_user}', 'gists_url': 'https://api.github.com/users/AmazingAng/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/AmazingAng/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/AmazingAng/subscriptions', 'organizations_url': 'https://api.github.com/users/AmazingAng/orgs', 'repos_url': 'https://api.github.com/users/AmazingAng/repos', 'events_url': 'https://api.github.com/users/AmazingAng/events{/privacy}', 'received_events_url': 'https://api.github.com/users/AmazingAng/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False},
'html_url': 'https://github.com/AmazingAng/WTF-Solidity',
'description': 'WTF Solidity 极简入门教程，供小白们使用。Now supports English! 官网: https://wtf.academy',
'fork': False, 'url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity',
'forks_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/forks',
'keys_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/keys{/key_id}',
'collaborators_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/collaborators{/collaborator}',
'teams_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/teams',
'hooks_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/hooks',
'issue_events_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/issues/events{/number}',
'events_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/events',
'assignees_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/assignees{/user}',
'branches_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/branches{/branch}',
'tags_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/tags',
'blobs_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/git/blobs{/sha}',
'git_tags_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/git/tags{/sha}',
'git_refs_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/git/refs{/sha}',
'trees_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/git/trees{/sha}',
'statuses_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/statuses/{sha}',
'languages_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/languages',
'stargazers_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/stargazers',
'contributors_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/contributors', 'subscribers_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/subscribers',
'subscription_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/subscription',
'commits_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/commits{/sha}',
'git_commits_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/git/commits{/sha}',
'comments_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/comments{/number}',
'issue_comment_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/issues/comments{/number}',
'contents_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/contents/{+path}',
'compare_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/compare/{base}...{head}',
'merges_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/merges',
'archive_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/{archive_format}{/ref}',
'downloads_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/downloads',
'issues_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/issues{/number}',
'pulls_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/pulls{/number}',
'milestones_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/milestones{/number}',
'notifications_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/notifications{?since,all,participating}',
'labels_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/labels{/name}',
'releases_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/releases{/id}',
'deployments_url': 'https://api.github.com/repos/AmazingAng/WTF-Solidity/deployments',
'created_at': '2022-04-02T05:33:11Z',
'updated_at': '2025-10-05T11:36:10Z',
'pushed_at': '2025-09-25T05:41:46Z',
'git_url': 'git://github.com/AmazingAng/WTF-Solidity.git',
'ssh_url': 'git@github.com:AmazingAng/WTF-Solidity.git',
'clone_url': 'https://github.com/AmazingAng/WTF-Solidity.git',
'svn_url': 'https://github.com/AmazingAng/WTF-Solidity',
'homepage': 'https://wtf.academy',
'size': 226927,
'stargazers_count': 13268,
'watchers_count': 13268,
'language': 'Solidity',
'has_issues': True,
'has_projects': True,
'has_downloads': True,
'has_wiki': True,
'has_pages': False,
'has_discussions': True,
'forks_count': 2297,
'mirror_url': None,
'archived': False,
'disabled': False,
'open_issues_count': 12,
'license': {'key': 'other', 'name': 'Other', 'spdx_id': 'NOASSERTION', 'url': None, 'node_id': 'MDc6TGljZW5zZTA='},
'allow_forking': True, 'is_template': False, 'web_commit_signoff_required': False,
'topics': ['airdrop', 'auction', 'blockchain', 'dapp', 'dapps', 'erc20', 'erc721', 'ethereum', 'merkle-tree', 'nft', 'open-source', 'signature-verification', 'smart-contracts', 'solidity', 'solidity-contracts', 'tutorial-code', 'web3'],
'visibility': 'public', 'forks': 2297, 'open_issues': 12, 'watchers': 13268, 'default_branch': 'main',
'permissions': {'admin': False, 'maintain': False, 'push': False, 'triage': False, 'pull': True},
'score': 1.0}]
